channels:
  - conda-forge
dependencies:
  - nodejs
  - pip
  - python=3.12
  - pip:
    - aws-cdk-lib
    - awscli
    - black
    - boto3
    - cachetools
    - clize
    - dataclass-wizard
    - ipykernel
    - ipython
    - mypy
    - nbconvert
    - nbformat
    - pytest
    - python-dotenv
    - requests
    - tqdm